# Generated by Django 3.2.15 on 2022-09-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('regId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('stream', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('roleName', models.CharField(max_length=20)),
                ('yearOfJoining', models.DateField()),
                ('yearOfPassing', models.DateField()),
                ('skills', models.CharField(max_length=200)),
                ('interests', models.CharField(max_length=200)),
                ('linkedInProfile', models.CharField(max_length=100)),
                ('yearsOfExperince', models.CharField(max_length=5)),
                ('expertise', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('startYear', models.DateField()),
                ('endYear', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('regId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuser.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=500)),
                ('regId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuser.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MasterEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituteName', models.CharField(max_length=100)),
                ('mastersSubject', models.CharField(max_length=50)),
                ('yearOfCompletion', models.DateField()),
                ('regId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuser.profile')),
            ],
        ),
    ]
