# Generated by Django 3.2.15 on 2022-09-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
