# Generated by Django 3.2.15 on 2022-09-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0002_alter_profile_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='regId',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='regID',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profileuser.profile'),
            preserve_default=False,
        ),
    ]
