# Generated by Django 3.2.15 on 2022-09-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0004_alter_workexperience_regid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
