# Generated by Django 3.2.15 on 2022-09-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0006_workexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='regID',
            new_name='regId',
        ),
    ]
