# Generated by Django 3.2.15 on 2022-09-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0007_rename_regid_workexperience_regid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='regId',
        ),
    ]
