# Generated by Django 3.2.15 on 2022-09-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0008_remove_workexperience_regid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
