# Generated by Django 3.2.15 on 2022-09-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0015_alter_masteredu_regid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='regId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workex', to='profileuser.profile'),
        ),
    ]
