# Generated by Django 3.2.15 on 2022-09-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0016_alter_workexperience_regid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='regId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyn', to='profileuser.profile'),
        ),
    ]
