# Generated by Django 3.2.15 on 2022-09-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0017_alter_notes_regid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yearOfJoining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yearOfPassing',
            field=models.DateField(blank=True, null=True),
        ),
    ]
