# Generated by Django 3.2.15 on 2022-09-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0018_auto_20220914_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteredu',
            name='yearOfCompletion',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedInProfile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yearOfJoining',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yearOfPassing',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yearsOfExperince',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='endYear',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='startYear',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
